### ISSUE TITLE
cannot open source file "digitaltwin_interface_client.h" (dependency of "sensors_interface.h"

### ISSUE THREAD

**Issue by yomagg** [Azure-Samples/mxchip-iot-devkit-pnp#10]
Hi,
It seems that the digitaltwin_interface_client.h file is missing in my compilation zoo and my "Arduino: Upload" command fails. Where can I find this file? Thanks!

**Comment by IvanJobs** [comment]
investigate now
@yomagg could you provide full log when "Arduino: Upload" failed in your case?

**Comment by IvanJobs** [comment]
@yomagg digitaltwin_interface_client.h belongs to the pnp version of azure-iot-sdk-c which should be downloaded when you install mxchip board using "Arduino Board Manager" command. you can also check c_cpp_properties.json under folder of .vscode in your workspace where you can probably find setttings for include paths.

**Comment by yomagg** [comment]
@IvanJobs thanks for your interesting answer. I checked the c_cpp_properties.json and I have found:
``
  "includePath": [
                "${workspaceFolder}",
                "C:\\Users\\magg\\AppData\\Local\\Arduino15\\packages\\AZ3166\\tools\\**",
                "C:\\Users\\magg\\AppData\\Local\\Arduino15\\packages\\AZ3166\\hardware\\stm32f4\\1.9.11-preview\\**"
            ],
``

I have also found the file digitialtwin_interface_client.h in 
``
C:\Users\magg\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.9.11-preview\system\azure-iot-sdk-c\digitaltwin_client\inc 
``

Should add this to .json config? 

It seems that my sketch is being uploaded, though - I checked the log and it finalizes with:
``
[Done] Uploaded the sketch: main.ino
``
So it makes me wonder if those two issues in the PROBLEMS tab in Visual Studio Code. 
![centrai_problems_tab](https://user-images.githubusercontent.com/4332691/75517711-31a36a80-59b4-11ea-9ac3-707f3f6bb3df.jpg)

has any real impact apart from being an information about impossibility of finding the paths to the files.

**Comment by yomagg** [comment]
When I add the path to json file:
``
 "C:\\Users\\magg\\AppData\\Local\\Arduino15\\packages\\AZ3166\\hardware\\stm32f4\\1.9.11-preview\\system\\azure-iot-sdk-c\\digitaltwin_client\\inc"
``
the problems in the "PROBLEM" tab disappear.

**Comment by IvanJobs** [comment]
@yomagg Thanks for your feedbacks. I think you don't need to add C:\Users\magg\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.9.11-preview\system\azure-iot-sdk-c\digitaltwin_client\inc to the json file, because "C:\\Users\\magg\\AppData\\Local\\Arduino15\\packages\\AZ3166\\hardware\\stm32f4\\1.9.11-preview\\**" should works.
So now you can upload your code successfully, but confusing includePath errors still exist under the PROBLEM tab, right?
Truth be told, I also encountered this includePath errors but with different error messages. I will continue to investigate this issue and give feedbacks later. Now I suggest just ignore them for a second as long as you can upload your code successfully.

**Comment by yomagg** [comment]
@IvanJobs It is weird. I removed the 'inc' folder from the includePath, and any errors are reported in the PROBLEMS tab ... I have no issues with modifying the code locally and uploading the code to the kit.

**Comment by IvanJobs** [comment]
@yomagg 
Firstly, I'm glad you somehow solved your own problem with weirdness. 
Maybe I can get rid of the weirdness here for you. 
After focusing on this issue for a while, I'm pretty sure where the problem is. 
In short words, please refer my pr: https://github.com/Azure-Samples/mxchip-iot-devkit-pnp/pull/14
In details, as you can see from my pr, the guide doc didn't tell it clearly to open a workspace or open a file, so I guess there must be some people opened the workspace file just as a text file. Then a bunch of includePath errors occurs,  but. if you open it as a workspace file, the c_cpp_properties.json would be generated automatically, and there would not be  any includePath errors then. 
If you open the workspace file as using ** File > Open Workspace...**, but still got includePath errors, here I guess something is wrong with C/C++ extension's intelliSense, and please let me know and provide enough details for me to re-generate the case you encountered, thx.

**Comment by IvanJobs** [comment]
to be closed later on.
