### ISSUE TITLE
Digital Twin Code Generator tool 0.6.0 - where is it? Is it called during Arduino:Upload?

### ISSUE THREAD

**Issue by yomagg** [Azure-Samples/mxchip-iot-devkit-pnp#11]
It's likely not the proper place to ask this question, however, I don't know where to post it. In some files, e.g., ``screen_interface.c`` or ``settings_interface.c``, there is a comment that the code was auto-generated by a tool and manual modifications to the code might be lost after code regeneration. I couldn't find the Digital Twin Code Generator tool mentioned in the comment. Is this an internal tool? Where can I find it? Does "Arduino:Upload" invoke the tool? It would be great if anybody can point me to some sort of documentation. Thanks!

``
This code was automatically generated by Digital Twin Code Generator tool 0.6.0.
Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
``

**Comment by dooriya** [comment]
@yomagg Thanks for reaching out!
 
For your question, 

> What is the Digital Twin Code Generator tool?

The Digital Twin Code Generator tool is a command line tool currently integrated with the [Azure IoT Tools](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-tools) VS Code extenstion. This tool allows IoT device developers to convert the [IoT Plug & Play model](https://github.com/Azure/IoTPlugandPlay/tree/master/DTDL) to language specific source code that runs on the device or gateway and helps on integrating IoT devices into Azure IoT Platforms more easily.

- For more information about how to use this tool, see also https://docs.microsoft.com/en-us/azure/iot-pnp/howto-develop-with-vs-vscode. 

- To learn more about Azure IoT Plug and Play, please read more about the official [PnP documents](https://docs.microsoft.com/en-us/azure/iot-pnp/overview-iot-plug-and-play).

> Does "Arduino:Upload" invoke the tool?

No. The CodeGen tool is only used for generating code skeleton, it has nothing to do with the **Arduino** extension. As you can see, most of the sample code in this repository is generated by this CodeGen tool,  that's why you can see the file comment like `This code was automatically generated by Digital Twin Code Generator tool ...` in each file that generated by this tool.

**Comment by yomagg** [comment]
Thanks!
