### ISSUE TITLE
Include errors

### ISSUE THREAD

**Issue by johnhaire89** [Azure-Samples/mxchip-iot-devkit-pnp#13]
I'm following the procedure to compile and upload the code at https://docs.microsoft.com/en-us/samples/azure-samples/mxchip-iot-devkit-pnp/sample/ and it seems that there are directories missing from the includePath 

```
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\username\Development\mxchip\mxchip-iot-devkit-pnp\Device\main.ino).
cannot open source file "digitaltwin_device_client_ll.h" (dependency of "src/mxchip_iot_devkit/pnp_device.h")
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\username\Development\mxchip\mxchip-iot-devkit-pnp\Device\main.ino).
```

I updated the includePath to include "${workspaceFolder}\\**" instead of ${workspaceFolder} and it seems to have helped.

Now I have missing files being referenced from digitaltwin_client_helper.h
```
cannot open source file "digitaltwin_device_client_ll.h"
cannot open source file "digitaltwin_interface_client.h"
```

It seems that these files are in the ESP Samples repo but not the mxchip repo.

**Comment by IvanJobs** [comment]
in my investigation.

**Comment by johnhaire89** [comment]
Just read through https://github.com/Azure-Samples/mxchip-iot-devkit-pnp/issues/10 and realised my mistake.

The instructions at https://github.com/Azure-Samples/mxchip-iot-devkit-pnp#compile-and-upload-code instruct users to follow the instructions for preparing the environment at https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-get-started#prepare-the-development-environment.

The latter used 
https://raw.githubusercontent.com/VSChina/azureiotdevkit_tools/master/package_azureboard_index.json instead of https://raw.githubusercontent.com/vschina/azureiotdevkit_tools/pnp/package_mxchip_board_preview_index.json for `arduino.additionalUrls`.



Thus, I ended up installing the board version `1.6.1` instead of `1.9.11-preview`.

**Comment by SpaBruis** [comment]
Thanks @johnhaire89, I had the old board version too because i have been playing with the MXChips a while back. The best way is indeed to press ctrl+shift+P, Type in "Preferences: Open User Settings", Open Settings (JSON):
![afbeelding](https://user-images.githubusercontent.com/55592439/75685183-73752f00-5c9a-11ea-9465-dc7ae45c26cf.png)
And paste the link: 
![afbeelding](https://user-images.githubusercontent.com/55592439/75685266-97d10b80-5c9a-11ea-9e2e-69bb2c266b1d.png)
Ctrl + Shift + P again -> Arduino Board manager -> filter on MX -> select 1.9.11-preview and press "Update"
![afbeelding](https://user-images.githubusercontent.com/55592439/75685461-e088c480-5c9a-11ea-9c9a-6bfaa4c8358b.png)

**Comment by IvanJobs** [comment]
@johnhaire89 Glad you got your own problem solved and truly we need to update arduino.additionalUrls. If there's no other problems here, I will close this issue later.

**Comment by IvanJobs** [comment]
problem solved, close the issue.
